modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/TheLMiffy1111/PackagedAuto/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/packagedauto"
authors="TheLMiffy1111"
[[mods]]
modId="packagedauto"
version="${file.jarVersion}"
displayName="PackagedAuto"
description="An Applied Energistics 2 addon that uses 'packages' to allow autocrafting with more than 9 items."

[[dependencies.packagedauto]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="NONE"
    side="BOTH"
